SELECT ?item ?esteka ?euskarazkoIzena ?irudia ?biztanleria WHERE {
  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "eu".
    ?item rdfs:label ?euskarazkoIzena.
  }
  { ?item wdt:P31 wd:Q2074737. }
  ?item (wdt:P131/(wdt:P131*)/^wdt:P527) wd:Q47588.
    ?item wdt:P1082 ?biztanleria.
    OPTIONAL { ?item wdt:P18 ?irudia. }
  ?esteka schema:about ?item;
    schema:inLanguage "eu";
    schema:isPartOf <https://eu.wikipedia.org/>.
}